rmagatti/auto-session

- README.md
- lua/auto-session-library.lua
- lua/auto-session.lua
- plugin/auto-session.vim
New flags should start as nil, unless the default behaviour of the
plugin is not the desired behaviour.
Setting the `auto_save_enabled = true` for example allows for a session
to be saved even when vim was first opened as a "pager". i.e passing in
parameters for reading from stdin.
Closes #13.
> Implement specific flags for auto saving and restoring and update docs

- README.md
- lua/auto-session.lua
Switched the evaluation of vim being opened with args or not to the
begining of the auto_save and auto_restore function flags.
Closes #24
> Fix auto save/restore getting triggered when in pager mode

- README.md
- lua/auto-session.lua
Disabling happens by setting the auto_save_enabled flag to false.
The auto save function still runs but checks the flag before actually
saving.
Currently if entering this state only restarting Neovim with an
uncorrupted or non-existent session will bring back auto saving.
Closes #27
> Disable auto saving when sourcing a session errors out.

- lua/auto-session.lua
Check if the deleted session is the current session and disable auto
saving for it when the DeleteSession command is used.
This prevents the session from being automatically saved when exiting
neovim after having deleted the current session.
Closes #29.
> Disable auto save after delete command

- lua/auto-session-library.lua
- lua/auto-session.lua
- plugin/auto-session.vim
Show the actual unescaped 'name' of the session instead of the full path
to the session + escaped name when showing completion options.
> Friendlier command completion

- lua/auto-session-library.lua
We need to call `unescape_dir` in windows.
Before
> Session saved at C:\Users\denil\AppData\Local\nvim-data/sessions/C:\Users\denil.vim
...site\pack\packer\start\auto-session\lua\auto-session.lua:173: Vim(mksession):E190: Cannot open "C:\Users\denil\AppData\Local\nvim-data/sessions/C:\Users\denil.vim" for writing
After
> Session saved at C:\Users\denil\AppData\Local\nvim-data/sessions/C++\%Users\%denil.vim
I am not sure if this is the best way to fix this. We could simplify the logic to only check` IS_WIN32` once.
Tested on Linux (WSL2) and Windows
Thank you.
> unescape windows path for save and restore session operation

- lua/auto-session.lua
**Use case**:
**Neovim**: v0.5.0-dev+1411-gb28d458f8
auto-session configured as below:
``` lua
local opts = {
auto_session_enable_last_session = true,
auto_session_enabled = true,
auto_session_root_dir = vim.fn.stdpath('data').."/sessions/",
log_level = 'info',
pre_save_cmds = {'lua G_cVim.fileExplorer.close()'}
}
```
No files in the `sessions` path.
Existing code finds no files.
https://github.com/rmagatti/auto-session/blob/main/lua/auto-session.lua#L110-L119
``` lua
for _, filename in ipairs(vim.fn.readdir(dir)) do
local session = AutoSession.conf.auto_session_root_dir..filename     
local last_edited = vim.fn.getftime(session)
if last_edited > latest_session.last_edited then
latest_session.session = session
latest_session.last_edited = last_edited
end
end
```
and as a result …
> Handle case where there are no session files

- lua/auto-session-library.lua
- lua/auto-session.lua
This addresses #45 by keeping track in memory of the last loaded session and using that instead of trying to get from cwd on SessionSave.
> Keep track of last loaded session. Closes #45

- lua/auto-session.lua
Setting this new setting to false will prevent creating new sessions
while continue updating existing sessions (created with :SaveSession)
Fixes #60
This preserves original behavior except for debug logging in `SaveSession` (I could not find a _nice_ way to preserve that ;-) ).
> feat: Add Auto-Create setting

- lua/auto-session.lua
Typo was potentially leading to auto-save not working.
Fixes #92.
> Fix typo related to auto_save

- lua/auto-session.lua
The session was still created correctly and everything works but the way
the error is presented makes it seem like the plugin just broke, making
it a debug log instead to make using git and non-git directories more
seamless.
Closes #131
> Address a seemingly breaking scenario when opening a non-git directory

- lua/auto-session-library.lua
Escape the file extension and search it only at the end of the session file name string.
Resolves #134
> Fix bad output of `current_session_name`

- lua/auto-session.lua
This PR implements my suggestion in #140, although frankly I should have waited to get your take first 😅. Was just pretty keen on it. Anyway, the changes include adding an `Autosession` command using the `vim.api.nvim_create_user_command`. This command can be expanded in the future but for now it takes two arguments `Autosession delete` or `Autosession search` both will use `vim.ui.select` to open the picker a user has configured e.g. Telescope or FZF or some custom function.
On confirming a selection it will restore or delete the session ~(*eventually*) for now, when I try and restore the session it doesn't work. I don't know if the path I'm using is incorrect for the session or what the right argument looks like~
> feat(commands): add Autosession commands using ui.select

- README.md
- lua/auto-session.lua
The idea came up because I have all my workspaces which I'd want to create sessions for in the same base folder.
So instead of specifying one by one, I wanted to just set the base path.
Using the `*` wildcard at the end of the path makes `vim.fn.simplify(vim.fn.expand(s))` return a string containing all the directories inside the base path. Then Lua's `string.find` returns a non-nil value if `s` contains `cwd`, thus producing a match, making suppressing or allowing everything under a base path easier.
> Add support for usage of base paths with wildcard for suppress_dirs and allowed_dirs properties

- lua/auto-session.lua
This fixes #145 by removing the usage of `vim.fs` which doesn't exist in stable nvim
> bugfix: use vim.fn.readdir over vim.fs

- lua/auto-session.lua
I found out, during normal usage, that `string.find` was also matching for "root" directories of a specified path.
E.g.: 
`auto_session_allowed_dirs` = { "/my/path/to/repo" }
If I open `vim` in `/my/path` and quit, a session is created for that directory too (since `/my/path` is also contained in the specified directory.
`string.gmatch` will split the string by line breaks and generate an iterator. The difference between this and what we had before the `string.find` usage is that this still supports the paths with wildcards, but it's gonna check each one for equality with `cwd` and will only match for fully qualified paths, instead of partial ones.
> fix(allowed_supress): use string.gmatch instead of string.find

- lua/auto-session.lua
Sometimes I run things like
```
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```
and I noticed I get the auto-session logs.
IMHO, auto-session should be skipped when run in headless mode.
Let me know what you think :)
PS: my first pr with lua code ever :)
> feat: disable in headless mode

- README.md
- doc/auto-session.txt
- lua/auto-session-autocmds.lua
- lua/auto-session-library.lua
- lua/auto-session.lua
This commit adds handling for when the cwd changes by setting callbacks
to both `DirChangedPre` and `DirChanged` autocmds.
Handling is as follows
DirChangedPre:
- Save the current session
- Clear all buffers `%bd!`. This guarantees buffers don't bleed to the
next session.
- Clear jumps. Also done so there is no bleading between sessions.
- Run the `pre_cwd_changed_hook`
DirChanged:
- Restore session using new cwd
- Run the `post_cwd_changed_hook`
Now when the user changes the cwd with `:cd some/new/dir` auto-session
handles it gracefully, saving the current session so there aren't losses and loading the session for the upcoming cwd if it
exists.
Closes #102.
> Add DirChangedPre and DirChanged handling

- lua/auto-session.lua
Many users had issues where they were using some plugins that changed
the cwd frequently and would run into an undesired situation with the
new feature. This commit makes it so the default behaviour is whatever
auto session used to do before implementing this feature so as to not
break other people's workflows.
Fixes #157 and #158
> Make the cwd_change_handling feature be disabled by default.

- lua/auto-session-library.lua
- lua/auto-session.lua
by default it can crash when the string contains % characters
> Change log behavior to not use format

- README.md
- lua/auto-session.lua
vim support to save additional setting, which file name `{session_file}x.vim` 
> :help mks
> If a file exists with the same name as the Session file, but ending in "x.vim" (for eXtra), executes that as well. You can use *x.vim files to
specify additional settings and actions associated with a given Session, such as creating menu items in the GUI version.
here is same pull request, I complete the feature base @nanozuki 's work Thanks♪(･ω･)ﾉ
https://github.com/rmagatti/auto-session/pull/89
* new hook named `save_extra_cmds`
* filter out `x.vim` from `:Autosession search`
here is sample, when you restore session, neovim will load `{session_file}x.vim` automatically. for this case, echo 'hello world', when you restore session.
```lua
require('auto-session').setup {
save_extra_cmds = { …
```
> add feature for saving extra data to session

- README.md
- lua/auto-session-autocmds.lua
- lua/auto-session-library.lua
- lua/auto-session.lua
This enables file tree integration with `nvim-tree` and `NERDTree`.
It is [fairly difficult](https://github.com/rmagatti/auto-session/issues/178) to get sessions and file tree browsers to play nicely together, but when you do, the result is spectacular.
As such, I thought I'd make it easier to integrate the two with a simple configuration option:
```lua
require 'nvim-tree'.setup {
auto_session_enable_file_tree_integration = true,
}
```
This *hopefully* fixes:
* https://github.com/rmagatti/auto-session/issues/178
* https://github.com/rmagatti/auto-session/issues/50
And would be a solution for people struggling with sessions/file trees elsewhere as well:
* https://github.com/preservim/nerdtree/issues/745
* https://github.com/preservim/nerdtree/issues/337
* …
> File tree integration with nvim-tree and NERDTree

- README.md
- lua/auto-session.lua
See https://github.com/rmagatti/auto-session/pull/179#issuecomment-1307567366
Save local options which will restore syntax highlighting, as well as `wrap` and `number` options
> revert filetype detect, save localoptions

- .github/workflows/docgen.yml
- README.md
- doc/auto-session.txt
- lua/auto-session.lua
Closes #181
Also fixes the help docs to work with the newest version of lemmy-help.
Reference:
https://github.com/numToStr/lemmy-help/pull/47
https://github.com/numToStr/lemmy-help/pull/37
There seems to be an issue still with parsing a vararg param:
https://github.com/numToStr/lemmy-help/issues/61
> Bump neovim version to v0.7.0

- lua/auto-session.lua
This PR is an attempt to fix session bypass if more than one buffers is opened and all opened buffers are on the bypass list. Currently the feature will not work properly if more than 1 buffers is opened
> Fix session bypass if more than one buffers opened

- lua/auto-session.lua
Problem:
When a UI that uses --embed closes channel, there are no UIs attached when the VimLeave autocommand is triggred, and auto-session detects this as headless mode.
Solution:
Don't detect Nvim invoked with --embed as headless mode.
Fix https://github.com/neovim/neovim/issues/22972
> fix: don't consider embedded mode headless mode

- lua/auto-session/init.lua
A bug about failing to save session was introduced in #225 . This PR fixes it.
Fix #226 .
> fix: session file name

- lua/auto-session/lib.lua
A bug about failing to save session was introduced in #227 on Windows. This PR fixes it.
I've isolated the changes to WIN32 now, so it'll not have regression on other OS
Fix #220
> fix: windows invert escappe dir

- lua/auto-session/session-lens/init.lua
I found the previewer cannot be turned on with builtin session_lens, seems the custom opts and default is reversed
> fix: session_lens config is overwritten

- lua/auto-session/init.lua
This fixes an issue where the auto_session_use_git_branch had no effect. I tested this on MacOS with nvim 0.9. The code that gets the branch name (`get_branch_name`) was executing, but the code that appended the branch name to the session was commented out in c3f35994 for some reason. The `get_branch_name` function is where the auto_session_use_git_branch option is checked and it will return an empty string if it is not set.
> Fix auto_session_use_git_branch functionality (#236)

- lua/auto-session/init.lua
- lua/auto-session/logger.lua
This is a very simple improvement to log messages displayed by the plugin, specifically the error when restoring a session fails.
I often find myself accidentally opening a session which is already open somewhere else, which usually causes Neovim to try and open files which are in use. I then realise that I've made a mistake and hit abort on the "are you sure you want to open the file" popup, which then causes the session restore to fail. Auto-session then displays an error message and very helpfully disables auto-save.
What this PR does is change the `to_print` function to avoid passing strings directly to `vim.inspect`, because that causes linebreaks to be displayed as literal `\n`'s in the restore session error message. I've also removed the indentation from the message, to make it …
> Improve log messages

- lua/auto-session/init.lua
Discovered when  you start `neovide` your root folder is `/` and if this folder is suppressed it still appears in a list.
my config 
```lua
return {
"rmagatti/auto-session",
config = function()
require("auto-session").setup({
log_level = "debug",
auto_session_suppress_dirs = { "~/", "~/Desktop", "~/Downloads", "/" },
session_lens = {
-- If load_on_setup is set to false, one needs to eventually call `require("auto-session").setup_session_lens()` if they want to use session-lens.
-- shorten_path = true,
load_on_setup = true,
theme_conf = { border = true },
previewer = false,
},
})
vim.keymap.set("n", "<S-D-p>", require("auto-session.session-lens").search_session, { noremap = true })
end,
}
```
> ignore tralling slash clean when folder = /

- lua/telescope/_extensions/session-lens.lua
Runing the `:Telescope session-lens` command causes a 'attempt to call a nil value' error. This pull request fixes that.
> Fix telescope extension

- README.md
- lua/auto-session/init.lua
- lua/auto-session/session-lens/actions.lua
- lua/auto-session/session-lens/init.lua
This `PR` should add functionality to avoid undesired buffer removal.
e.g. If you want to keep `terminal` buffer open and switch back and forth from one session to another session. it makes sense to keep it open.
> add filter for buffer deleation option

- README.md
- doc/auto-session.txt
- lua/auto-session/init.lua
Adds `:SessionPurgeOrphaned` and
`require('auto-session').PurgeOrphanedSessions()` commands to purge all sessions with non-existent working directories.
Fixes #232
> feat: Add command to purge orphaned sessions

- README.md
I was happy to find that there is a shortcut to delete sessions right within the session lens picker. Unfortunately, it is not mentioned anywhere in the readme. Specifically, I expected it to be listed with the session alternation shortcut, so that's where I suggest it is added.
> Add session lens delete shortcut to readme

- lua/auto-session/init.lua
Execute AutoSaveSession on VimLeavePre instead. Session save net functionality should remain the same.
Upstream issue:
https://github.com/neovim/neovim/issues/21856#issuecomment-1514723887
Fixes #268
Workaround inspired by:
https://github.com/mrjones2014/smart-splits.nvim/pull/159
> Work around upstream issue executing shell commands on `VimLeave`

- lua/auto-session/init.lua
Add a function to understand if a session exists for the given current working directory.
This is pretty helpful for start page plugins like mini.starter and others.
By calling this function when nvim is opened to a workspace folder the starter page can determine whether to show a 'restore session' option or not.
> add AutoSession.session_exists_for_cwd() function

- lua/auto-session/init.lua
I have no experience developing in LUA or VIM/NeoVim plugins.
Please check possible side-effects that I might overlook.
This is so simple that I expect it to be wrong :-)
> #257 [BUG] :SessionSave doesn't actually accept an argument

- README.md
- lua/auto-session/init.lua
Based on @zamotany's code here:
https://github.com/rmagatti/auto-session/issues/223#issuecomment-1666658887
If Lazy is present, we wait to automatically restore the session until we get the VeryLazy event and there's no Lazy window still up.
If Lazy isn't present, loading works as before.
> Fix #223, where session is loaded into Lazy window

- lua/auto-session/init.lua
- lua/auto-session/lib.lua
Easiest repro is only have a new buffer (not saved to a file) and exit. We'll  try to close that window and generate an error.
To fix, we wrap `Lib.close_unsupported_windows` in a `pcall`. In general, not great to eat all errors but we're making our best effort to close all of the unsupported windows and there are a bunch of edge cases there so this seems like the most reasonable path to me.
Also added a missiing local
> Fix tried to close last window error

- README.md
- lua/auto-session/init.lua
> Add no-restore hook

- lua/auto-session/autocmds.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/session-lens/actions.lua
- lua/auto-session/session-lens/init.lua
- lua/auto-session/session-lens/library.lua
Unify the session loading logic between Telesecop session-lens and AutoSession search so that we always use the session file to load the session (vs relying on changing directory). Set a flag to make sure cwd_change_handling (if enabled) doesn't also try to restore the session This also fixes a session load failure when a session with a git branch name is selected from Telescope session-lens or Autosession search.
Removed the non-functional (as far as I can see) code for buftypes_to_ignore. That code would not bwipeout a buffer if it matched but the buffers get wiped out by the sourcing the session file anyway and having that code generates an error when the buffer is opened in another process which interrupts the session swap. Made the option deprecated and asked anyone using it to …
> Unify session selection logic, Fixes #287

- README.md
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
Introduces two new arguments:
args_allow_single_directory (default: true)
Allows launching nvim with single a argument that's a directory.
auto-session will try to load a session from that directory if possible
args_files_auto_save (default false)
Allow saving a session even when launched with a file argument (or
multiple files/dirs). It does not load any existing session first.
That's not super useful on it's own by args_files_auto_save can be a
callback function that conditionally returns true or false
Fixes #303 #316
> Args support

- lua/auto-session/init.lua
I had an issue on Windows where I was getting the following error when restoring session:
```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: ...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:634: Expected object key string but found T_END at character 2
stack traceback:
[C]: in function 'decode'
...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:634: in function 'write_to_session_control_json'
...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:757: in function 'restore'
...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:799: in function 'AutoRestoreSession'
...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:1038: in function <...l/share/nvim/lazy/auto-session/lua/auto-session/init.lua:1012>
Press …
```
> ensure json is decoded correctly even if it's content is multiline

- .github/workflows/tests.yml
- .gitignore
- Makefile
- README.md
- doc/auto-session.txt
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/session-lens/actions.lua
- lua/auto-session/session-lens/init.lua
- lua/auto-session/session-lens/library.lua
- tests/allowed_dirs_spec.lua
- tests/args/args_files_enabled_spec.lua
- tests/args/args_not_enabled_spec.lua
- tests/args/args_setup_spec.lua
- tests/args/args_single_dir_enabled_spec.lua
- tests/auto_save_spec.lua
- tests/bypass_save_by_filetypes_spec.lua
- tests/create_enabled_spec.lua
- tests/cwd_change_handling_spec.lua
- tests/extra_sesssion_commands_spec.lua
- tests/git_spec.lua
- tests/hooks_spec.lua
- tests/lib_spec.lua
- tests/minimal.lua
- tests/minimal.vim
- tests/session_control_spec.lua
- tests/setup_spec.lua
- tests/test_lib.lua
I somehow accidentally removed the whitespace for the Makefile step that installs plenary. It should auto install now. Let me know if it doesn't work for you!
Also, what do you think about running the tests on commit? I'm not sure how GH does it but I assume something like that would be possible?
> Unit test fixes and run them as a GH action

- .github/workflows/tests.yml
- doc/auto-session.txt
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/session-lens/init.lua
- tests/git_spec.lua
- tests/test_lib.lua
It's a bit of a bandaid. Might be nice to rethink config at some point.
> fix: annotate types to eliminiate diagnostics and speed up tests

- README.md
- doc/auto-session.txt
- lua/auto-session/init.lua
Still show the last error at the end (if there is one). Setting `silent_restore` to `false` will restore the current behavior of stopping at the first error.
Improves #325
Fixes #337
> Keep sourcing the session even if there's an error

- lua/auto-session/init.lua
- tests/cmds_spec.lua
- tests/legacy_file_names_spec.lua
Forgot to check for legacy session names in `session_exists_for_cwd`
> fix: #286 for legacy session file names

- README.md
- doc/auto-session.txt
- lua/auto-session/init.lua
- lua/auto-session/session-lens/init.lua
Partially fixes #344 (but it's still better to ignore dashboards in the config)
Also add a quick section in docs about dashboards
> Don't try to autosave a session for the same directory we're loading from. Also customizable keymaps for session lens

- .github/workflows/docgen.yml
- .gitignore
- README.md
- doc/auto-session.txt
- lua/auto-session/autocmds.lua
- lua/auto-session/config.lua
- lua/auto-session/health.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/session-lens/actions.lua
- lua/auto-session/session-lens/init.lua
- tests/allowed_dirs_spec.lua
- tests/args_files_enabled_spec.lua
- tests/args_single_dir_enabled_spec.lua
- tests/cmds_custom_dir_spec.lua
- tests/cmds_enable_toggle_spec.lua
- tests/cmds_spec.lua
- tests/extra_sesssion_commands_spec.lua
- tests/git_spec.lua
- tests/lib_spec.lua
- tests/session_control_spec.lua
- tests/session_lens_spec.lua
- tests/suppress_dirs_spec.lua
- tests/test_lib.lua
The new config should be backwards compatible with the previous names but I'll still mention it in the breaking changes thread just in case.
Also includes:
- some errors were incorrectly being shown during session restoring: #358
- [added support for symlinks in allowed/suppressed dirs](https://github.com/rmagatti/auto-session/issues/275#issuecomment-2304173159)
- fixes sometimes not being able to delete a session from Telescope picker
- document allowed_dirs/suppressed_dirs more clearly: #350
- update docs to show how to change size of picker: #356
> Config overhaul

- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/session-lens/init.lua
- tests/cmds_spec.lua
Noticed that it was creating empty extra command files after my changes due to an empty table vs nil mistake. Only place that uses the return is in `save_extra_cmds_new` and it relies on the return being nil when there are no commands.
Also made picker sort by modified as the default rather than leaving it up to whatever the underlying command decided it should sort by (or no sort at all). Having a consistent, reasonable default seems better.
> fix: don't create empty extra command files

- tests/mini-tests/test_ui.lua
Noticed unit tests on windows were sometimes failing so extending timeouts
> test: make mini test delay longer for windows

- .github/ISSUE_TEMPLATE/bug_report.md
Now that we have a checkhealth section, makes sense to request it as part of bug reports
> docs: request checkhealth output on issue form

- lua/auto-session/config.lua
Came up while looking into #369
> fix: Clear old config flag if setup called again

- lua/auto-session/session-lens/init.lua
Telescope merged my fix for:
https://github.com/nvim-telescope/telescope.nvim/issues/3265
So now we can return nil to have a correct count and still have delete sessions from the Telescope picker work
> fix: return nil in session lens entry maker

- README.md
- lua/auto-session/init.lua
- tests/manually_named_autosave_spec.lua
Should only impact manually named sessions, making them work more
how I think people would expect them to work.
If you're using a manually named session (either through ':SessionSave
mysession', `:SessionSearch`, or `:SessionRestore mysession`) then we'll
now auto-save to that session on exit instead of always autosaving to
the session derived from the cwd.
Fixes #389
> feat: autosave manually named sessions,  #386

- doc/auto-session.txt
- lua/auto-session/config.lua
So it won't generate warnings if you only set some of them
> fix: mark more settings as optional

- README.md
- doc/auto-session.txt
- lua/auto-session/config.lua
- lua/auto-session/init.lua
- tests/ls_stop_on_restore_spec.lua
- tests/test_lib.lua
But don't do this on startup as calling vim.lsp.get_clients() causes a
small but noticeable delay on startup.
> Fix: #208 stop LSs when restoring session

- lua/auto-session/autocmds.lua
Wonder why there is no completion for SessionSave, please close the PR if it's not relevant.
> feat: Add session name completion for SessionSave

- lua/auto-session/lib.lua
**Describe the bug**
Whilst I have '/' in my suppressed_dirs config property, a session is created for this directory in certain situations.
**To Reproduce**
1. `cd /`
2. `nvim`
3. Open another previously stored session.
4. Close vim with `:qa`.
5. Reopen vim and list the stored sessions — a session for '/' is created.
**Expected behavior**
I expect no session for '/'.
**Remarks**
I narrowed it down to `Lib.find_matching_directory` using a too naive `gsub` pattern. This pull request contains an updated pattern that in my opinion works better, and leaves the single '/' intact.
> Root directory not respected as suppressed_dir

- lua/auto-session/lib.lua
- tests/lib_spec.lua
When launching as `nvim /`, session_name was getting set to "" because / was getting removed as a trailing separator. If the path is entirely "/", don't remove /. This lets session loading (and suppressing) work as expected.
Fixes #411
> fix: Session handling for nvim /

- lua/auto-session/autocmds.lua
- lua/auto-session/init.lua
- tests/get_cwd_spec.lua
> fix: Fix session relying on `getcwd` without specifying global (-1)

- lua/auto-session/autocmds.lua
Very minor, just realized I hadn't hooked up the preview view correctly when using Snacks.
> fix(snacks): Preview should be off by default

- README.md
- doc/auto-session.txt
- lua/auto-session/config.lua
- lua/auto-session/init.lua
The default error handler ignores "E490: No fold found" errors. For all
other errors, the default handler will show an error message and return
false, which will disable auto-saving.
Users can override that behavior by setting Config.restore_error_handler
to a function that takes a string and returns false if auto-saving
should be disabled.
Fixes #409
> feat: add customizable restore error handler

- .github/workflows/tests.yml
- README.md
- doc/auto-session.txt
- lua/auto-session/autocmds.lua
- lua/auto-session/config.lua
- lua/auto-session/health.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- tests/purge_old_sessions_spec.lua
Had some time so implemented the purging feature, largely with the code from #404 (thanks @holmanb!)
Add config option, purge_after_days which is disabled by default. If set
to a number greater than 0, then sessions older than that will be
deleted automatically.
Fixes #404
Requires nvim >= 0.10 (noted in the documentation and shows a warning on startup/in checkhealth if the `purge_after_days` is set and nvim <= 0.10)
> feat: support for purging old sessions

- doc/auto-session.txt
- lua/auto-session/autocmds.lua
- lua/auto-session/config.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- tests/cmds_spec.lua
If there are only unnamed / empty listed buffers, delete the current session on
exit.
Listed as a breaking change because it's enabled by default (though the
change seems very minor)
Fixes: #426
> feat!: auto-delete empty session on exit

- README.md
- doc/auto-session.txt
- lua/auto-session/config.lua
- lua/auto-session/git.lua
- lua/auto-session/health.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- tests/git_spec.lua
If there are modified buffers, it pops a confirmation dialog. If the
session for the new branch isn't loaded, then autosave is disabled.
Fixes #127
> feat(git): branch tracking with auto-save/restore

- README.md
- doc/auto-session.txt
- lua/auto-session/autocmds.lua
- lua/auto-session/config.lua
- lua/auto-session/session-lens/init.lua
Rename `theme_conf` to `picker_opts` to better represent what it does.
Deprecated `shorten_path` (even harder this time) and `path_display`
when under the `session_lens` config block. Both of those are Telescope
specific and should be in `picker_opts`. We'll automatically detect when
they're still in `session_lens` and set them in `picker_opts` and show
the old config warning `checkhealth`.
Added support for configuring the session picker when using Snacks via
`picker_opts`.
Change is only listed as breaking because the `previewer` option was
removed. The default is still that no preview is displayed (for both
Telescope and Snacks) but if you want to turn preview on for the session
picker for some reason, set the appropriate field in `picker_opts`
(`previewer = true,` for Telescope and …
> refactor(Config)!: Clean up picker customization

- lua/auto-session/init.lua
- tests/restore_error_handler_spec.lua
somewhat related to #409 , extracted out of #456 
This is an error I often run into when restoring sessions, especially when multiple work streams overlap and code moves around
> ignore E16 invalid range when attempting to restore folds

- lua/auto-session/lib.lua
- tests/lib_spec.lua
This issue was causing the session lens to break when extra command files are present, since telescope expects to be passed a dense array
Discovered in the process of iterating on #456
> fix: nil filtering issue in `Lib.get_session_list`

- .github/workflows/tests.yml
- Makefile
- README.md
I looked into the GH action failures and they were caused by a non-deterministic error (sometimes segfault, sometimes LuaJIT assertion failure, sometimes works) in `restore_error_handler_spec.lua` with nvim < 0.10. I think it's time to drop support for those earlier versions.
They'll still work with the current build but I don't think we should commit to supporting them.
Separately, I added a macos testing target.
@rmagatti before this change is integrated, can you create a tag named `pre-nvim-0.10` (or whatever you'd prefer) that marks the last version of tested support for older versions?
> chore!: drop support for nvim <=0.10

- lua/auto-session/health.lua
- lua/auto-session/pickers/fzf.lua
- lua/auto-session/pickers/init.lua
- lua/auto-session/pickers/select.lua
- tests/mini-tests/test_ui.lua
Only happens if vim.ui.select is the chosen picker.
I somehow mixed up the functions when refactoring so it would open the delete picker when asked for the session picker!
Also show selected picker in checkhealth
> fix(picker.select): fix loading/deleting

- README.md
- doc/auto-session.txt
- lua/auto-session/config.lua
- lua/auto-session/init.lua
- lua/auto-session/lib.lua
- lua/auto-session/logger.lua
- tests/hooks_spec.lua
`pre_save` and `pre_restore` are now passed the session name (this
supercedes https://github.com/rmagatti/auto-session/issues/443) and if one of the cmds returns false, then auto saving
or restoring are prevented.
Fixes https://github.com/rmagatti/auto-session/issues/493
Marked as breaking in the unlikely case someone has an existing hook
that happens to be returning false already
Also, refactor logger to use Config.log_level directly
> feat(hooks)!: pre_save/restore can stop auto save/restore 

- README.md
- doc/auto-session.txt
- lua/auto-session/config.lua
- lua/auto-session/health.lua
We don't store any state in Lib.logger anymore so vim.tbl_isempty is false (methods in the metatable don't count)
Fixes issue mentioned in #495
> fix(health): Lib.logger is empty normally now
