rmagatti/auto-session

lua/auto-session-library.lua, lua/auto-session.lua
When enabled, auto-session keeps track of the last session and attempts
to load it when a `RestoreSession` is called but can't find a session to
restore based on the current directory.
=> Add last_session feature

README.md, lua/auto-session-library.lua, lua/auto-session.lua, plugin/auto-session.vim
This PR reworks where session files are stored by default and add a enable/disable flag as well as refactors some code to snake_case.
=> Rework where session files are stored by default and add a enable/disable flag

README.md, lua/auto-session.lua, plugin/auto-session.vim
=> Expose existing DeleteSession command

lua/auto-session-library.lua, lua/auto-session.lua
This Pull request make SaveSession, RestoreSession, DeleteSession work in Windows. This change is not covering every case but it work in my configuration.
=> Initial support for Windows

lua/auto-session.lua, plugin/auto-session.vim
When deleting sessions allow the user to use
completion to find the right session to delete.
=> Session filename completion

lua/auto-session-library.lua
=> Use string:gsub instead of vim.fn.expand to check filereadable

lua/auto-session.lua, plugin/auto-session.vim
=> Add DisableAutoSave command.

README.md, lua/auto-session.lua
pretty much the title
let me know if there's a better way to do it and I will happily adjust my code 😃
=> chore: allow hooks to be lua functions

README.md
Packer instructions and config I use.
=> Update readme with packer instructions

lua/auto-session-library.lua
- `get_file_name` -- gets a filename from a path
- `get_file_extension` -- gets a file extension from a path
- `current_session_name` -- returns the current session name
=> Add three lib helper functions

README.md
=> Add instructions for configuring lualine to show the current session

README.md
=> Add README note about disabling the plugin.

README.md
I don't know if you'd like to have this example in the docs. If not just ignore and close the PR :)
=> Update hook example to restore nvim-tree status

lua/auto-session-library.lua, lua/auto-session.lua
=> fix: use vim.fn.expand on DeleteSession.

README.md, lua/auto-session.lua
=> Bypass on only buffer of specific file types

README.md, lua/auto-session.lua, plugin/auto-session.vim
Pass to it a path that is the name of a saved session. Command-completion is provided.
=> * Add new command :RestoreSessionFromFile. 

README.md, lua/auto-session.lua
Add missing documentation for the `Autosession` command.
Also fix the prompts for the command pickers
=> docs(README): add Autosession command description

.github/workflows/docgen.yml, lua/auto-session-autocmds.lua, lua/auto-session.lua
=> Allow false as well as nil for cwd_change_handling key to disable

lua/auto-session-library.lua, lua/auto-session.lua
I'm not sure if you're interested, but I think its nicer to have the logs as notifications instead of print messages
=> Moving logger to vim.notify

lua/auto-session.lua
=> Only save extra cmds if config is passed in

doc/auto-session.txt, lua/auto-session.lua
=> Make the actual sourcing of a session silent

.gitignore
=> Ignore docs/tags

lua/auto-session/init.lua, lua/auto-session/lib.lua
=> fix: windows file name

lua/auto-session/init.lua
fixes https://github.com/rmagatti/auto-session/issues/245
=> fix git branch not considered when deleting session

lua/auto-session/init.lua
=> Fix SessionRestoreFromFile command

lua/auto-session/session-lens/init.lua
Hi there :)
First of all, thank you for your work on this project! I was not sure if I should file this PR in this repo, or in [rmagatti/session-lens](https://github.com/rmagatti/session-lens), but as session-lens is also included in this repo, I decided to file it here (I hope that's fine for you).
As your telescope extension just uses the `find_files` picker internally, all settings set for this picker in telescope, e.g:
```lua
pickers = {
find_files = {
mappings = {
i = { ['<CR>'] = actions.select_tab_drop }
},
},
}
```
also affect session-lens. The example above leads to undesirable and unexpected results (at least on my machine :D).
When creating a custom picker, settings won't bleed from telescopes pickers into session-lens, thus solving problems, like the one I mentioned above.
The …
=> [Telescope Extension] Use custom picker instead of `find_files`

doc/auto-session.txt, lua/auto-session/init.lua
=> Add ability to control whether to silently restore session or not

lua/auto-session/init.lua
🤦 forgot to add the filepath on _both_ branches
=> Add silent restore option

lua/auto-session/session-lens/init.lua
=> Remove default picker theme

README.md, lua/auto-session/init.lua, lua/auto-session/lib.lua
Also added a setting to disable closing the unsupported windows just in case. Although, I'm not sure if I added it correctly or in the right place.
=> Made the changes requested in #230

.github/workflows/docgen.yml, doc/auto-session.txt
- Update the `checkout` action to version `v4`
- Update the `git-auto-commit-action` to version `v5`
=> ci: Update GitHub Actions and commit message format

README.md
- Add a lazy config block at the top to get most ppl going quickly
- Moved showing session name in Lualine lower down so it's not in the middle of the options explanation
- Explain what session lens is a little more
=> [chore] Minor documentation cleanup

README.md, lua/auto-session/init.lua
Let auto_session_create_enabled take a function that lets a user customize when a session can be created automatically
=> Fix #234 auto_session_create_enabled take a func

.gitignore, Makefile, README.md, lua/auto-session/autocmds.lua, lua/auto-session/init.lua, lua/auto-session/lib.lua, tests/allowed_dirs_spec.lua, tests/args/args_files_enabled_spec.lua, tests/args/args_not_enabled_spec.lua, tests/args/args_setup_spec.lua, tests/args/args_single_dir_enabled_spec.lua, tests/auto_save_spec.lua, tests/bypass_save_by_filetypes_spec.lua, tests/create_enabled_spec.lua, tests/cwd_change_handling_spec.lua, tests/extra_sesssion_commands_spec.lua, tests/git_spec.lua, tests/hooks_spec.lua, tests/minimal.vim, tests/session_dir_custom_spec.lua, tests/session_dir_no_slash_spec.lua, tests/setup_spec.lua, tests/suppress_dirs_spec.lua, tests/test_files/other.txt, tests/test_files/test.txt, tests/test_lib.lua
I saw your comments from a while back about wanting to clean the code up and I figured getting some unit tests would be a good first step. There's still a lot of stuff that isn't covered but I wanted to make sure you're ok with the general approach. thanks!
=> Unit testing

lua/auto-session/lib.lua
Also make window closing more resilient if a window closes unexpectedly (I've seen it happen with Neogit where closing the Neogit window will close other windows, e.g. Oil)
=> fix: #342 don't close terminal windows

README.md
=> docs(readme): Use opts for example Lazy.nvim config

README.md
Just fix a typo in the readme file.
=> Typo in readme.me

lua/auto-session/config.lua
=> Fix old config names message always displayed

.github/workflows/tests.yml, lua/auto-session/autocmds.lua, tests/cwd_change_handling_spec.lua
Only applies when cwd_change_handling = true
=> fix: #399 clear this_session when cwd is changed

lua/auto-session/init.lua, lua/auto-session/lib.lua, tests/git_spec.lua
When `use_git_branch=true, args_allow_single_directory=true`, the code wasn't adding the git branch name to the launch directory argument.
Also refactored some of the git functions into Lib and added a unit test for both `nvim .` and `nvim git_proj`.
Fixes #419
=> fix: launching w/ git dir argument doesn't restore

lua/auto-session/git.lua
Have to use the same autosaving logic when switching branches so the config options are all followed.
=> fix: use full autosave logic on branch switch

lua/auto-session/init.lua, tests/git_spec.lua, tests/restore_error_handler_spec.lua
There was a logic error when using the custom restore_error function. Added unit test and should work now.
=> fix: #325 custom restore_error_handler not called

lua/auto-session/config.lua
Provide a warning if sessionoptions is missing buffers
Fixes #449
=> fix(checkhealth): Check sessionoptions for buffers

README.md, lua/auto-session/config.lua, lua/auto-session/init.lua, lua/auto-session/lib.lua, tests/ignore_filetypes_on_save_spec.lua
Fixes #447
I had some time so I made the changes to #448 (except for the minimum version change).
@rmagatti feel free to close if this isn't how you want it to be.
Also, got embedded stylua formatting set up so there are some formatting cleanups to the README
=> feat: Add ignore_filetypes_on_save option

.github/workflows/docgen.yml, README.md, doc/auto-session.txt, lua/auto-session/autocmds.lua, lua/auto-session/config.lua, lua/auto-session/git.lua, lua/auto-session/init.lua, lua/auto-session/lib.lua, tests/auto_delete_spec.lua, tests/custom_session_tag_spec.lua, tests/git_spec.lua, tests/lib_spec.lua
Fixes #465 
Also, overhauled the readme:
- add a features section
- fill out details section to describe how things work
- add git section
- update gifs to be more zoomed in, hopefully making them easier to see
- move some more arcane features to wiki (e.g. argument handling, last session). I'm still a bit on the fence if this is the best way to handle it so I'm open to pulling those sections back into the readme if you think that's better, @rmagatti
=> feat: add custom_session_tag
